enum CharacterActionTypes {
  SEARCH_CHARACTERS       = 'SEARCH_CHARACTERS',
  GET_CHARACTERS_SUCCESS  = 'GET_CHARACTERS_SUCCESS',
  GET_CHARACTERS_FAILURE  = 'GET_CHARACTERS_FAILURE'
}

export default CharacterActionTypes;
