enum CharacterActionTypes {
  SEARCH_CHARACTERS       = 'SEARCH_CHARACTERS',
  GET_CHARACTER_DETAILS   = 'GET_CHARACTER_DETAILS',
  GET_CHARACTERS_SUCCESS  = 'GET_CHARACTERS_SUCCESS',
  GET_CHARACTERS_DETAILS_SUCCESS = 'GET_CHARACTERS_DETAILS_SUCCESS',
  GET_CHARACTERS_FAILURE  = 'GET_CHARACTERS_FAILURE'
}

export default CharacterActionTypes;
